services:
  mediaflow-proxy:
    ports:
      - "8888:8888"
    env_file:
      - .env
    restart: always
    logging:
      options:
        max-size: 1g
    image: ghcr.io/nn34223/mediaflow-proxy:latest
